#!/bin/bash


if [ -e ZeroNet-master ]

then

cd ZeroNet-master

python2 zeronet.py  --tor disable --ui_ip "*"  --ui_port $PORT --ui_password $PASS

else

curl -sSL https://github.com/HelloZeroNet/ZeroNet/archive/master.tar.gz -o new.tar.gz
tar -zxvf new.tar.gz
cd Zero*
mv  ./plugins/disabled-UiPassword ./plugins/UiPassword
curl -sSL https://github.com/utgerauer/clone/blob/master/torrc -o torrc
fi

while :; do sleep 31104000 ; done
